[ui.window]
margin_top = 200
margin_bottom = 200
margin_start = 200
margin_end = 200

[ui.window.box]
width = 520
orientation = "vertical"

[ui.window.box.search]
spacing = 0
hide = false

[ui.window.box.search.input]
hide = false

[ui.window.box.search.icon]
hide = true

[ui.window.box.search.spinner]
hide = true

[ui.window.box.scroll]
width = 520

[ui.window.box.scroll.list]
width = 520
max_width = 520
min_width = 420
max_height = 400
spacing = 2

[ui.window.box.scroll.list.item]
spacing = 0

[ui.window.box.scroll.list.item.icon]
hide = true

[ui.window.box.scroll.list.item.text]
spacing = 0
orientation = "vertical"

[ui.window.box.scroll.list.item.text.sub]
hide = false